<!--HOW TO COMPLETE THIS FORM:-->

<!--
1. Checkboxes in this document appear as follows: 

- [ ] This is a checkbox 

To check a checkbox, replace [ ] by [x], as follows: 

- [x] This is a checked checkbox 

Note that older versions of RStudio (versions lower than 1.3) may not create a formatted checkbox but will leave the original characters, i.e., literally "[ ]" or "[x]". It's fine to submit a PDF in this form.
 
2. For text answers, simply type the relevant text in the areas indicated. A blank line starts a new paragraph. 
 
3. Comments (like these instructions) provide additional instructions throughout the form. There is no need to remove them; they will not appear in the compiled document. 

4. If you are comfortable with Markdown syntax, you may choose to include any Markdown-compliant formatting in the form. For example, you may wish to include R code chunks and compile this document in R Markdown.
-->

This form documents the artifacts associated with the article (i.e., the data and code supporting the computational findings) and describes how to reproduce the findings.


# Part 1: Data

- [ ] This paper does not involve analysis of external data (i.e., no data are used or the only data are generated by the authors via simulation in their code).

<!--
If box above is checked and if no simulated/synthetic data files are provided by the authors, please skip directly to the Code section. Otherwise, continue.
-->

- [x] I certify that the author(s) of the manuscript have legitimate access to and permission to use the data used in this manuscript.

<!-- If data are simulated using random number generation, please be sure to set the random number seed in the code you provide -->

## Abstract



The dataset consists of simulated and real data of EEG-fMRI. The simulated data along with data generation code is available. We provide generation code for four types of simulated graph under 2 different noise models, as detailed in Appendix K. We will provide a download link for a simulated dataset for these four types of graphs and with the sample size 100, and the dimension 50,100,150. 
The real data is available upon request. Since we do not own the original dataset of  concurrent measurements of EEG-fMRI, we kindly ask to send the request to the original authors referenced in the manuscript. 


## Availability


- [x] Data **are** publicly available.
- [ ] Data **cannot be made** publicly available.

If the data are publicly available, see the *Publicly available data* section. Otherwise, see the *Non-publicly available data* section, below.

### Publicly available data

- [x] Data are available online at:[here](https://drive.google.com/drive/folders/1EbHl0Q2oE_ME3WjLWINdSlg_M9VJM0Qy?usp=share_link)

- [ ] Data are available as part of the paper’s supplementary material.

- [ ] Data are publicly available by request, following the process described here:

- [x] Data are or will be made available through some other mechanism, described here:


The data we use is originally from Sadaghiani et al. (2010). Please contact the first author to request the data. The simulated data are available in the above link. Partial simulated data, i.e, the data that runs the sample complexity in section 7.2 of the manuscript is not available online due to the fact that the size is too big (~1TB). But the data generation code is provided so practitioners can generate data on their own.  

Reference

Sadaghiani, S., Scheeringa, R., Lehongre, K., Morillon, B., Giraud, A. L., & Kleinschmidt, A. (2010). Intrinsic connectivity networks, alpha oscillations, and tonic alertness: a simultaneous electroencephalography/functional magnetic resonance imaging study. Journal of Neuroscience, 30(30), 10243-10250.


### Non-publicly available data

<!--
The Journal of the American Statistical Association requires authors to make data accompanying their papers available to the scientific community except in cases where: 1) public sharing of data would be impossible, 2) suitable synthetic data are provided which allow the main analyses to be replicated (recognizing that results may differ from the "real" data analyses), and 3) the scientific value of the results and methods outweigh the lack of reproducibility.

Please discuss the lack of publicly available data. For example:
-	why data sharing is not possible,
-	what synthetic data are provided, and 
-	why the value of the paper's scientific contribution outweighs the lack of reproducibility.
-->

## Description

### File format(s)

<!--
Check all that apply
-->
- [ ] CSV or other plain text.
- [x] Software-specific binary format (.Rda, Python pickle, etc.): pkcle
- [ ] Standardized binary format (e.g., netCDF, HDF5, etc.): 
- [ ] Other (please specify):

### Data dictionary

<!--
A data dictionary provides information that allows users to understand the meaning, format, and use of the data.
-->

- [x] Provided by authors in the following file(s): Under the directory `data/README.md`
- [ ] Data file(s) is(are) self-describing (e.g., netCDF files)
- [ ] Available at the following URL: 

### Additional Information (optional)

<!-- 
OPTIONAL: Provide any additional details that would be helpful in understanding the data. If relevant, please provide unique identifier/DOI/version information and/or license/terms of use.
-->

# Part 2: Code

## Abstract

The code contains source files and testing files. We briefly outline the content of each directory. The `code/synth_data` directory contains files to generate synthetic data and script files to generate a batch of synthetic data. The `code/src` contains all the source code. We do not provide the codes for other comparing methods as we do not possess the ownership. Under the directory `code/tests`,  the directory `notebook` contains all the step-by-step instruction and visualization code, the `script` folder contains the execution script. The `code/experiments` directory contains the data preprocessing code and graph estimation code for real data. 


## Description

### Code format(s)

<!--
Check all that apply
-->
- [x] Script files
    - [x] R
    - [x] Python
    - [ ] Matlab
    - [ ] Other: 
- [x] Package
    - [x] R
    - [x] Python
    - [ ] MATLAB toolbox
    - [ ] Other: 
- [x] Reproducible report 
    - [ ] R Markdown
    - [x] Jupyter notebook
    - [ ] Other:
- [x] Shell script
- [ ] Other (please specify): 

### Supporting software requirements

#### Version of primary software used

R      version 3.6.0
Python version 3.7.3

#### Libraries and dependencies used by the code

- R-packages
    - wordspace_0.2-6   
    - fields_12.5
    - viridis_0.6.1
    - viridisLite_0.4.0
    - spam_2.7-0
    - dotCall64_1.0-1
    - plotly_4.10.0
    - ggplot2_3.3.5    
    - pracma_2.3.3
    - R.matlab_3.6.2
    - far_0.6-5
    - nlme_3.1-139     
    - matrixcalc_1.0-5
    - poweRlaw_0.70.6
    - fgm_1.0
    - mvtnorm_1.1-2    
    - fda_5.4.0
    - deSolve_1.30
    - fds_1.8
    - RCurl_1.98-1.5
    - rainbow_3.6
    - pcaPP_1.9-74
    - MASS_7.3-51.3
    - Matrix_1.2-17    
    - RSpectra_0.16-0
    - doParallel_1.0.16
    - iterators_1.0.10
    - foreach_1.4.4  
- Python packages
    please check the `environment.yml` under `code/`.

### Supporting system/hardware requirements (optional)

Platform: x86_64-conda_cos6-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

All experiments are run on a cluster and no GPUs are required. Any single run of the experiment can be run on a standalone desktop. However, if practitioners want to test different variables to generate ROC curves, it is highly recommended to use a cluster. 

### Parallelization used

- [ ] No parallel code used
- [x] Multi-core parallelization on a single machine/node
    - Number of cores used: 8-160
- [ ] Multi-machine/multi-node parallelization 
    - Number of nodes and cores used: 

### License

- [x] MIT License (default)
- [ ] BSD 
- [ ] GPL v3.0
- [ ] Creative Commons
- [ ] Other: (please specify)


### Additional information (optional)

<!--
OPTIONAL: By default, submitted code will be published on the JASA GitHub repository (http://github.com/JASA-ACS) as well as in the supplementary material. Authors are encouraged to also make their code available in a public code repository, such as on GitHub, GitLab, or BitBucket. If relevant, please provide unique identifier/DOI/version information (e.g., a Git commit ID, branch, release, or tag). If the code and workflow are provided together, this section may be omitted, with information provided in the "Location" section below.
-->

# Part 3: Reproducibility workflow

<!--
The materials provided should provide a straightforward way for reviewers and readers to reproduce analyses with as few steps as possible. 
-->

## Scope

The provided workflow reproduces:

- [ ] Any numbers provided in text in the paper
- [x] The computational method(s) presented in the paper (i.e., code is provided that implements the method(s))
- [x] All tables and figures in the paper
- [ ] Selected tables and figures in the paper, as explained and justified below:

## Workflow

### Location

The workflow is available:

<!--
Check all that apply, and in the case of a Git repository include unique identifier, such as specific commit ID, branch, release, or tag.
-->
- [ ] As part of the paper’s supplementary material.
- [x] In this Git repository: The git respository will be made public if accepted. Now we include the contents under the directory `code/`
- [ ] Other (please specify):

<!--
Indicate where the materials (generally including the code, unless in a separate location and indicated in the previous section) are available. We strongly encourage authors to place their materials (but not large datasets) in a Git repository hosted on a site such as GitHub, GitLab, or BitBucket. If the repository is private during the review process, please indicate the location where it will be available publicly upon publication, and also include the materials as a zip file (e.g., obtained directly from the Git hosting site) as supplementary materials.
-->


### Format(s)

<!--
Check all that apply
-->
- [ ] Single master code file 
- [x] Wrapper (shell) script(s)
- [x] Self-contained R Markdown file, Jupyter notebook, or other literate programming approach
- [ ] Text file (e.g., a readme-style file) that documents workflow
- [x] Makefile
- [ ] Other (more detail in *Instructions* below)

### Instructions

Each simulated experiment is consisted of three steps (i) generate simulated data (ii) run the proposed algorithm (w/ variable selection) (iii) visualize the results.
The code for the first step is under the directory `code/synth_data`. The file for the second step is under `code/tests` or the proposed algorithm can be run in batch by running the script files in `code/tests`. The tool to visualize the results is under  `code/tests/notebook`. Each directory also contains the `README.md` file for more detailed instruction.

### Expected run-time

Approximate time needed to reproduce the analyses on a standard desktop machine:

- [ ] < 1 minute
- [ ] 1-10 minutes
- [ ] 10-60 minutes
- [ ] 1-8 hours
- [ ] > 8 hours
- [x] Not feasible to run on a desktop machine, as described here:

### Additional information (optional)

<!--
OPTIONAL: Additional documentation provided (e.g., R package vignettes, demos or other examples) that show how to use the provided code/software in other settings.
-->

# Notes (optional)

<!--
OPTIONAL: Any other relevant information not covered on this form. If reproducibility materials are not publicly available at the time of submission, please provide information here on how the reviewers can view the materials.
-->
